### ISSUE TITLE
CDI-Unit broken from Weld 2.4.2.Final on

### ISSUE THREAD

**Issue by OliWolff** [BrynCooke/cdi-unit#101]
CDIUnit: 3.1.4
Weld 2.4.2.SP1, 2.4.2.Final
Apache Deltaspike 1.7.2
While trying to upgrade to current weld: 2.4.2.SP1 all tests broke: MethodNotFound Exception on  
org.jglue.cdiunit.internal.WeldTestUrlDeployment#89

Reason: With https://issues.jboss.org/browse/WELD-2314 / https://github.com/weld/api/pull/55 they changed the constructor of org.jboss.weld.metadata.BeansXmlImpl and added a new parameter "boolean isTrimmed"

org.jglue.cdiunit.internal.WeldTestUrlDeployment#89
org.jglue.cdiunit.internal.WeldTestUrlDeployment#94

**Comment by Krigu** [comment]
+1
Is there any plan to fix this in the near future?

**Comment by seanf** [comment]
Should be fixed by #105.
