### ISSUE TITLE
@AdditionalPackages/@AdditionalClasspath fails finding classes on Jenkins in Linux setup

### ISSUE THREAD

**Issue by q1j8** [BrynCooke/cdi-unit#102]
Annotations works fine running locally on windows development machince, but on Jenkins in Linux env.

Build output:
<Building jar>
…
08:39:48 [INFO] — maven-jar-plugin:3.0.2:jar (default-jar) @ proposal-description —
08:39:48 [INFO] Building jar: /usr/data/jenkins2/workspace/xt_feature_feature_nrp-2566-FKU6VXG6M5BWWOYPB6DZ37MQXUBENW7KE34TKNOIDVV2VYWNSJGA@2/proposal-description/target/proposal-description-0.0.1-SNAPSHOT.jar
…
<Running test>
08:39:58 Running dk.nykredit.proposaldescription.exposure.api.ProposalDescriptionFacadeIT
08:39:58 2017-03-03 08:39:57,845 na DEBUG org.jglue.cdiunit.internal.WeldTestUrlDeployment - CDI classpath entries discovered:
08:39:58 2017-03-03 08:39:57,845 na DEBUG org.jglue.cdiunit.internal.WeldTestUrlDeployment - file:/usr/data/jenkins2/workspace/xt_feature_feature_nrp-2566-FKU6VXG6M5BWWOYPB6DZ37MQXUBENW7KE34TKNOIDVV2VYWNSJGA%402/proposal-description/target/proposal-description-0.0.1-SNAPSHOT.jar
...
08:39:58 2017-03-03 08:39:57,846 na DEBUG org.jglue.cdiunit.internal.WeldTestUrlDeployment - file:/usr/data/jenkins2/workspace/xt_feature_feature_nrp-2566-FKU6VXG6M5BWWOYPB6DZ37MQXUBENW7KE34TKNOIDVV2VYWNSJGA@2/proposal-description/target/surefire/surefirebooter5823997269050975354.jar
08:39:58 2017-03-03 08:39:57,846 na DEBUG org.jglue.cdiunit.internal.WeldTestUrlDeployment - file:/usr/data/jenkins2/workspace/xt_feature_feature_nrp-2566-FKU6VXG6M5BWWOYPB6DZ37MQXUBENW7KE34TKNOIDVV2VYWNSJGA%402/proposal-description/target/test-classes/
...
08:39:58 2017-03-03 08:39:57,896 na WARN org.reflections.Reflections - could not create Dir using jarFile from url file:/usr/data/jenkins2/workspace/xt_feature_feature_nrp-2566-FKU6VXG6M5BWWOYPB6DZ37MQXUBENW7KE34TKNOIDVV2VYWNSJGA%25402/proposal-description/target/proposal-description-0.0.1-SNAPSHOT.jar. skipping.
08:39:58 java.lang.NullPointerException
08:39:58 at java.util.zip.ZipFile.<init>(ZipFile.java:207)
08:39:58 at java.util.zip.ZipFile.<init>(ZipFile.java:149) 

---
The jar has folder ending with GA@2, while the cdi runner lookup sees GA%402.
In the end it reports an error regarding folder GA%25402.
%40” is hex for @, and “%25” is hex for “%”, so it seems to go wrong somewhere in the "search" process using the org.reflections library?

**Comment by clausfod** [comment]
I guess it has been solved in the latest release of org.reflections -> https://github.com/ronmamo/reflections/issues?utf8=%E2%9C%93&q=is%3Aissue%20java.lang.NullPointerException

Maybe an upgrade to 0.9.11 is needed to fix this ?

**Comment by seanf** [comment]
This should have been fixed by #105 in CDI-Unit 4.0. Please let me know if it's still happening though.
