### ISSUE TITLE
Support Gradle 4.x and IntelliJ 2017.2

### ISSUE THREAD

**Issue by brunoessmann** [BrynCooke/cdi-unit#117]
Gradle 4.x uses separate output directories for each JVM language. As such CDI-Unit can no longer populate the CDI classpath correctly. 

IntelliJ 2017.2 is also affected since with this version IntelliJ no longer uses the same output folders as Gradle. These output folders have a different structure as well and CDI-Unit cannot determine the CDI classpath for them either.

**Comment by popfalushi** [comment]
Sorry for offtop, but are there any plans for 4.0.1 release dates? As far as I understand this issue will be fixed in 4.0.1 but I couldn't find any information about its release date. Google Groups discussion board seems dead - no one is answering.

**Comment by seanf** [comment]
Fix released as part of 4.0.1.
