### ISSUE TITLE
Decentralise documentation maintenance

### ISSUE THREAD

**Issue by seanf** [BrynCooke/cdi-unit#122]
@BrynCooke Андрей Попфалуши on the mailing list pointed out that the documentation on the website still talks about cdi-unit 3.1.2.

I'd like to find a way to share the responsibility for maintaining the cdi-unit docs, which are currently part of the jglue.org website. As I mentioned in #108, one option might be to migrate the cdi-unit docs to readthedocs.org, where they can be maintained as part of the source tree, in the same pull requests which include code changes. 

However, [GitHub Pages](https://pages.github.com/) could also work (hosted as http://bryncooke.github.io/cdi-unit by default, unless cdi-unit is moved to another GitHub organization). I think we could follow https://docs.travis-ci.com/user/deployment/pages/ plus https://docs.travis-ci.com/user/deployment#Conditional-Releases-with-on%3A eg

```yml
on: 
  branch: master 
  condition: $WELD_VERSION = 3.0.0.Final
```
(`condition "${TRAVIS_BUILD_NUMBER}.1" = "${TRAVIS_JOB_NUMBER}"` might work too)

I'm happy to do the work (or give it a try) once we settle on something, but it would really help if I could see the source code for the cdi-unit docs, and at some point you would need to flip the relevant switch, eg to enable GitHub Pages in the repository settings. What do you think @BrynCooke ?

**Comment by BrynCooke** [comment]
I am more than happy for this to happen.
Being realistic here, I am a hindrance to this project at the moment. This is unlikely to change unless I start working on projects that use CDI again, but I'm just not in the relevant space work wise for that to happen.

The original CDI unit docs were unfortunately done in wordpress. So HTML is what we have to work with. I'm going to try and pull this out in to github pages to see what happens. If it works then it's perhaps something we could start with. I don't have a particular preference over read the docs though.

**Comment by BrynCooke** [comment]
I took a stab at converting the current docs:
http://bryncooke.github.io/cdi-unit

I'm going to shut down the wordpress server that the old dcs were running on at the end of the month. It was a nightmare to maintain.

What do you think?

**Comment by BrynCooke** [comment]
I've set up a redirect on the old site to point to the new doc URL.

**Comment by seanf** [comment]
That's excellent, thanks @BrynCooke! 

~Where is the git repo for the docs?~ Oh, it's https://github.com/BrynCooke/cdi-unit/blob/master/docs/index.md, great. 
~How is that being picked up by GitHub Pages?~ I see that you can just use a **docs** directory now: https://github.com/blog/2228-simpler-github-pages-publishing

Note that the URL on the github page is still pointing to http://jglue.org/cdi-unit, which you might not want.
