### ISSUE TITLE
Failure in successive tests when a @ViewScoped bean depends on another @ViewScoped bean

### ISSUE THREAD

**Issue by nikospara** [BrynCooke/cdi-unit#123]
Hello,

When a `@ViewScoped` bean depends on another `@ViewScoped` bean, every test *after the first one* fails. 

The failure message for the 3.x line used to be:

    WELD-001303: No active contexts for scope type javax.faces.view.ViewScoped

With 4.x the error is more descriptive and pointing to the proposed solution:

    IllegalStateException: WELD-000229: Contextual reference of Managed Bean [class ...]
        with qualifiers [@Default @Any @Named] is not valid after
        container 6d8d88ef-461c-47d5-a577-bfefd6d20df1 shutdown

I have traced the reason to the `static Map<String, Object> viewMap` field of `org.jglue.cdiunit.internal.jsf.ViewContext` and to the fact that Weld is created and started anew for each test (see `org.jglue.cdiunit.CdiRunner` methods `createTest()` and `methodBlock()`). The problem is that, after the first time a test is run, some view-scoped beans are found in the *static* map, referring to the old, disposed Weld instance.

The proposed solution is to make the `viewMap` field non-static because there is no point in sharing a bean instance between runs since container is created anew.

**Comment by seanf** [comment]
Thanks for the fix @nikospara!

**Comment by nikospara** [comment]
Thank *you* for a most useful tool :)
