### ISSUE TITLE
cdi-unit 4.0.1 not working with weld-se 2.4.4.Final

### ISSUE THREAD

**Issue by ioana-mocan** [BrynCooke/cdi-unit#130]
I'm trying to upgrade cdi-unit from 3.1.3 to 4.0.1 but I get this error and I tried different versions of weld-se, weld-se-core, weld-core-impl
Can you please tell me which version of weld-se should work with cdi-unit 4.0.1?
org.jboss.weld.exceptions.DeploymentException: 
WELD-001408: Unsatisfied dependencies for type CdiUnitInitialListener with qualifiers @Default
  at injection point [BackedAnnotatedField] @Inject private org.jglue.cdiunit.ContextController.listener
  at org.jglue.cdiunit.ContextController.listener(ContextController.java:0)

**Comment by cschabl** [comment]
cdi-unit 4.0.2 and weld-se-core 2.4.6.Final works for me.

**Comment by seanf** [comment]
The test matrix for CDI-Unit actually includes Weld SE 2.4.4.Final (and has done for a while): https://github.com/BrynCooke/cdi-unit/blob/496b154513b20c4d1a79dd1d683a2ec6655febd5/.travis.yml#L27-L44

The quickstart info now has a little more information about adding the Weld SE dependency: http://bryncooke.github.io/cdi-unit/#quickstart

Please re-open if this is still a problem.

**Comment by totoweb69** [comment]
I am using cdiunit 4.0.1 on my project. I am migrating this project to jdk 17, so i have to migrate to version 4.0.2.Final. But it seems that cdiunit is not compatible with this version of weld. Is there a plan to fix that, or is there a workaround ?

**Comment by ikysil** [comment]
Dear @totoweb69 

Could you please clarify what component/library the version `4.0.2.Final` is related to.
I assume it is Weld SE version - given that we don't use suffixes for cdi-unit versions.

If so, that version of Weld - 4.0.x - and matching version of CDI spec - 3.x - are not supported by cdi-unit - see #195
