### ISSUE TITLE
Mocks during PostConstruct

### ISSUE THREAD

**Issue by Rosthouse** [BrynCooke/cdi-unit#64]
Hey

I was wondering if there is a chance to use Mocks during PostConstruct. So far it seems that in the CDIRunner, it will run a method annotated with `@PostConstruct` before the Junit `@Before` annotated method. However, if I need the mock already returning mocked values in the `@PostConstruct`, I have no way of doing this.

It's probably better to show an example. I took this (mostly ) from the user guide.

Let's have a class Starship such as:

```java
class Starship {
 
  @Inject
  Engine engine; //We don't know the exact engine that this ship will have.
  String engineState;
 
  @PostConstruct
  void warmup(){
    engineState = engine.warmup();
  }

  void start() {
    engine.start();
  }
}
```
Now let's say that engine.warmup() normally returns "Warming up". During a test however, I don't want to start the whole engine. So the mock should return "System test" instead.

```java
@RunWith(CdiRunner.class)
class TestStarship {
 
  @Inject
  Starship starship;
 
  @Produces
  @Mock // Mockito will create a mock for us.
  Engine engine;
  
  @Before
  public void before() {
    Mockito.when(engine.warmup()).thenReturn("System Test");
  }
 
  @Test
  public void testWarmUp() {
    assertEquals("System Test", starship.enginestate);
  }
}
```

This is probably not the ideal test case, but I hope it shows what I mean :)

**Comment by fedy2** [comment]
I've a similar problem. In the `PostConstruct` I use the value returned by `engine.warmup();` but it is null because the mock is not configured.

**Comment by exabrial** [comment]
Having the same problem, even if you use a getter.

**Comment by MikeIsMike** [comment]
Hi I have a similar problem. I don't want to run the actual @PostConstruct method as it starts a service that I do not want to start during test time until after I set up my test cases. It seems that doNothing is only set up after the object is constructed and the @PostConstruct function is run. Is there a way to mock the @PostConstruct function before it is run?

**Comment by ikysil** [comment]
Hi @MikeIsMike 

This issue is very old. Could you please try with a newer version of cdi-unit and open the new issue if this still could be reproduced.

I would much appreciate it if you include a link to a reproducer project hosted on GitHub or other similar platforms.

Thank you

**Comment by exabrial** [comment]
@MikeIsMike We solved this by writing a lighter-weight Mockito/Junit5 extension: https://github.com/exabrial/mockito-object-injection

This does not start a CDI container, so it's useless for integration tests (which CDI Unit is for), but it does provide true isolation with mocks for Unit Testing.

**Comment by MikeIsMike** [comment]
Hi @ikysil @exabrial, thank you both for your prompt response : )
Sorry I was not very clear about my current situation and did not check your Repo name carefully. The organisation I work in uses the Spring framework (not CDI) and Junit4. I will find another workaround for my issue. Thanks for your time.
