### ISSUE TITLE
broken dependency convergence

### ISSUE THREAD

**Issue by tkruse** [BrynCooke/cdi-unit#86]
Hi,

cdi-unit transitively includes guava 15 and guava 13. This breaks projects which enforce dependency convergence. Minimally it would be nice if only one guava version was transitively included.

To play nicely, cdi-unit could help by using a flat dependency layout.

Also see:
https://noclassdeffound.wordpress.com/2014/04/07/dealing-with-dependency-chain-issues-in-maven/
https://maven.apache.org/guides/introduction/introduction-to-optional-and-excludes-dependencies.html

Also, the documentation in github readme and the cdi-unit homepage still mention version 3.1.2, would be nice to update that to 3.1.3, I guess.

**Comment by seanf** [comment]
Guava was removed in 4.1.0, which was released yesterday.

Please let me know if this is still an issue.
